---
title: "Filelist"
author: "Thomas Bech-Thomassen"
date: "25. nov. 2015"
output:
  word_document: default
  pdf_document:
    latex_engine: xelatex
  html_document: default
---

## About this list ##
This is a list of files produced during an internship August 3rd -- December 2nd 2015.

The list includes filename, relative path and a short description of the purpose and function of the files.
R scripts have been commented, thus this document does not provide extensive documentation of their inner workings, but rather the context and purpose.

| File path  	| Description  	|
|:---	|:---	|
|  FisheriesAdvice/__figure2.R__ 	|  A simple R-script to produced figure 2 in the Fisheries Advice outline example 	|
|  FisheriesAdvice/__figure3.R__ 	|  A simple R-script to produced figure 3 in the Fisheries Advice outline example 	|
|  FisheriesAdvice/__figure4.R__ 	|  A simple R-script to produced figure 4 in the Fisheries Advice outline example 	|
|  FisheriesAdvice/__figure5.R__ 	|  A simple R-script to produced figure 5 in the Fisheries Advice outline example 	|
|  FisheriesAdvice/__figureYY.R__ 	|  A simple R-script to produced figure YY in the Fisheries Advice outline example 	|
|  keys-lists/__gear.list__ 	|  A list of gears used in the STECF landings data. Includes regulated gears, and can be used as a lookup table for renaming gears. E.g. from "R-OTTER" TO "OTTER TRAWL". It may be a good idea to combine it with stecf-gear.list, if possible.	|
|  keys-lists/__guild.list__ 	|  A list of 160 species (mainly marine fish), their scientific and common name, feeding guild, size guild. 	|
|   keys-lists/__regions-list__	|   A list of ICES squares, based on the ICES Official Catch database. Can be used to assign Ecoregion and subregion names to data. Be careful with aggregation (see ICES Official Catch Statistics metadata)	|
|  keys-lists/__species.list__ 	|  A list of 12345 aquatic species, their FAO-codes, scientific and common name. This list is used to translate FAO-species codes to scientific names, which can then be use to designate a guild, using the guild.list. 	|
|  keys-lists/__stecf-gear.list__ 	|  A list of gears used in the STECF economic & transversal datasets. These are more generalised, and does not include specific gear names ("purse seine"), but rather gear type ("surrounding nets"), their data codes, and towed/static designations. 	|
|   keys-lists/__stecf-fishingtech.list__	|   A shorter version of the gear list, including only fishing tech codes, long name and towed/static designation	|
|   ices/__dataGrabber.R__	|   A script that gets data from ICES official catches,  STECF Economic & Transversal, and STECF Landings databases. Also checks for directories to put the downloaded data in, and creates them if necessary. Datagrab does not occur if data has already been downloaded (i.e. a file with similar name exists)	|
|  fleet-characterisation/__capacity.graphs.R__ 	|  A script to produce graphs for characterising the ICES ecoregions in terms of fishing capacity, catches(species, guilds) and catch value. This file should probably be split into several scripts, doing only one thing, which can then be sourced from another script. 	|

